use_default_settings: true

server:
  secret_key: "sntllm-searxng-secret-please-change-in-production"
  limiter: false
  image_proxy: false
  base_url: "http://localhost:8888/"

ui:
  default_locale: "pt-BR"
  theme_args:
    simple_style: auto

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

outgoing:
  request_timeout: 5.0
  max_request_timeout: 15.0
